<?php require_once('../models/user.php'); ?>
<?php Session::pagePermission(0); ?>
<!DOCTYPE html>
<html>
    <head>
        <?php include 'includes/head.inc'; ?>
        <title>Default</title>
    </head>
    <?php include 'includes/header.inc'; ?>
    <body>
        <section class="box">
            <?php Session::msg(); ?>
            <div class="top-bar">
                <h1>Usuários</h1>
                <?php if (Session::permission(1)): ?>
                    <a href="new-user" class="btn btn-add"><i class="fa fa-plus"></i> Adicionar</a>
                <?php endif; ?>
            </div>
            <table class="table">
                <tr>
                    <td>Nome</td>
                    <td>E-mail</td>
                    <td>Ação</td>
                </tr>
                <?php User::loadAll(); ?>
            </table>
        </section>
        <?php include 'includes/scripts.inc'; ?>
    </body>
</html>
